original_data_path = "C:/Users/trist/OneDrive/Dokumente/UZH/BA/06_Code/DeFeSyn/data/churn"
categorical_columns = [
    'Geography',
    'Gender',
    'HasCrCard',
    'IsActiveMember',
    'Exited'
]

baseline_dir = "C:/Users/trist/OneDrive/Dokumente/UZH/BA/06_Code/DeFeSyn/exp/churn/runs/ctgan/ctgan_baseline/"
baseline_model_name = "ctgan_churn_baseline.pt"

dir = "C:/Users/trist/OneDrive/Dokumente/UZH/BA/06_Code/DeFeSyn/exp/churn/runs/ctgan/"
metrics = ["DCR", "NNDR", "AdversarialAccuracy", "Disclosure", "JS", "KS", "BasicStats", 'PCA', 'Consensus', 'Correlation', 'Utility', 'Distribution']

model_type = "ctgan"
dataset_name = "churn"
keys = ["Geography", "Gender", "Age"]
target = 'Exited'
seed = 42
iterations = 300