seed=42

[deconsyn_params]
dataset_name = "churn"
data_root = "data/churn/"
categorical_columns = [
    'Geography',
    'Gender',
    'HasCrCard',
    'IsActiveMember'
]
target = "Exited"

n = 3
epochs = 1
iterations = 300
topology = "ring"
k = 4
p = 0.1
alpha = 1.0
gen_model_type = "ctgan"
log_level = "info"
