seed=42
parent_dir = "exp/adult/ddpm_mlp_best"
real_data_path = "data/adult/"
num_numerical_features = 6
model_type = "mlp"
device = "cpu"

[deconsyn_params]
dataset_name = "adult"
data_root = "data/adult/"
categorical_columns = [
        "workclass",
        "education",
        "marital-status",
        "occupation",
        "relationship",
        "race",
        "sex",
        "native-country"
]
target = "income"

n = 4
epochs = 30
iterations = 300
topology = "ring"
k = 4
p = 0.1
alpha = 1.0
gen_model_type = "tabddpm"
log_level = "info"


[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    1024,
    512,
]
dropout = 0.0 #0.1,0.2

[diffusion_params]
num_timesteps = 1000 #100
gaussian_loss_type = "mse"

[train.main]
steps = 1
lr = 0.001809824563637657
weight_decay = 0.0
batch_size = 256 #4096 #256

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 54000
batch_size = 10000
seed = 0

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"
